/**
 * Preset Themes for Design System
 * 100% Token-driven themes for Metro OCC and White-label custom operations.
 */

import { ThemeConfig } from '../types/schema';
import { DEFAULT_DESIGN_TOKENS } from '../tokens/defaultTokens';

export const PRESET_THEMES: Record<string, ThemeConfig> = {
  // 1. OCC Master Dark (Default)
  'occ-dark': {
    id: 'occ-dark',
    name: 'اتاق کنترل OCC (پیش‌فرض)',
    englishName: 'OCC Master Dark',
    description: 'پالت استاندارد و صنعتی مرکز کنترل با هایلایت زمردی و کنتراست عمیق مشکی متالیک',
    category: 'dark',
    isDark: true,
    badge: 'صنعتی OCC 🟢',
    previewColor: '#020617',
    cardPreviewColor: '#0f172a',
    accentColor: '#10b981',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#10b981',
        primaryHover: '#059669',
        accent: '#10b981',
        accentGlow: 'rgba(16, 185, 129, 0.25)',
        background: '#020617',
        backgroundHeader: 'rgba(2, 6, 23, 0.88)',
        surface: 'rgba(255, 255, 255, 0.04)',
        surfaceHover: 'rgba(255, 255, 255, 0.07)',
        surfaceAlt: 'rgba(255, 255, 255, 0.025)',
        surfacePill: 'rgba(255, 255, 255, 0.06)',
        border: 'rgba(255, 255, 255, 0.1)',
        borderAlt: 'rgba(255, 255, 255, 0.06)',
        text: '#f8fafc',
        textSecondary: '#94a3b8',
        textMuted: '#64748b',
        glow1: 'rgba(37, 99, 235, 0.12)',
        glow2: 'rgba(99, 102, 241, 0.10)',
        glow3: 'rgba(16, 185, 129, 0.08)',
      },
    },
  },

  // 2. OCC Tactical Night Vision (Red/Black)
  'occ-night-vision': {
    id: 'occ-night-vision',
    name: 'دید در شب تاکتیکی OCC (قرمز/مشکی)',
    englishName: 'OCC Tactical Night Vision',
    description: 'طراحی مونوکروم قرمز-مشکی با کنتراست فوق‌بالا مطابق استانداردهای دیسپچینگ نظامی و اتاق‌های تاریک کنترل',
    category: 'dark',
    isDark: true,
    badge: 'دید در شب OCC 🔴',
    previewColor: '#000000',
    cardPreviewColor: '#140406',
    accentColor: '#ef4444',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#ef4444',
        primaryHover: '#dc2626',
        accent: '#ef4444',
        accentGlow: 'rgba(239, 68, 68, 0.5)',
        background: '#000000',
        backgroundHeader: 'rgba(12, 2, 4, 0.96)',
        surface: 'rgba(220, 38, 38, 0.08)',
        surfaceHover: 'rgba(239, 68, 68, 0.16)',
        surfaceAlt: 'rgba(185, 28, 28, 0.05)',
        surfacePill: 'rgba(239, 68, 68, 0.14)',
        border: 'rgba(239, 68, 68, 0.4)',
        borderAlt: 'rgba(239, 68, 68, 0.22)',
        text: '#fee2e2',
        textSecondary: '#fca5a5',
        textMuted: '#ef4444',
        glow1: 'rgba(239, 68, 68, 0.18)',
        glow2: 'rgba(185, 28, 28, 0.14)',
        glow3: 'rgba(248, 113, 113, 0.1)',
      },
    },
  },

  // 3. Shiraz Turquoise Cyber
  'shiraz-cyber': {
    id: 'shiraz-cyber',
    name: 'فیروزه‌ای سایبر شیراز',
    englishName: 'Shiraz Turquoise Cyber',
    description: 'طراحی شیشه‌ای و نئونی مدرن با تم فیروزه‌ای اصیل شهر شیراز و درخشش سایبری',
    category: 'dark',
    isDark: true,
    badge: 'نئون فیروزه‌ای 💎',
    previewColor: '#03121e',
    cardPreviewColor: '#082f49',
    accentColor: '#06b6d4',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#06b6d4',
        primaryHover: '#0891b2',
        accent: '#06b6d4',
        accentGlow: 'rgba(6, 182, 212, 0.35)',
        background: '#03121e',
        backgroundHeader: 'rgba(3, 18, 30, 0.92)',
        surface: 'rgba(6, 182, 212, 0.06)',
        surfaceHover: 'rgba(6, 182, 212, 0.1)',
        surfaceAlt: 'rgba(6, 182, 212, 0.035)',
        surfacePill: 'rgba(6, 182, 212, 0.09)',
        border: 'rgba(6, 182, 212, 0.18)',
        borderAlt: 'rgba(6, 182, 212, 0.09)',
        text: '#f0fdfa',
        textSecondary: '#99f6e4',
        textMuted: '#5eead4',
      },
    },
  },

  // 4. Midnight OLED Black
  'midnight-oled': {
    id: 'midnight-oled',
    name: 'دید در شب OLED (مشکی ۱۰۰٪)',
    englishName: 'Midnight OLED Black',
    description: 'مشکی خالص برای مانیتورهای OLED و حداقل مصرف انرژی و صفر بودن خستگی چشم در شیفت شب',
    category: 'dark',
    isDark: true,
    badge: 'خالص OLED ⚡',
    previewColor: '#000000',
    cardPreviewColor: '#121212',
    accentColor: '#22c55e',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#22c55e',
        primaryHover: '#16a34a',
        accent: '#22c55e',
        accentGlow: 'rgba(34, 197, 94, 0.3)',
        background: '#000000',
        backgroundHeader: 'rgba(0, 0, 0, 0.95)',
        surface: 'rgba(18, 18, 18, 0.9)',
        surfaceHover: 'rgba(30, 30, 30, 0.95)',
        surfaceAlt: 'rgba(10, 10, 10, 0.9)',
        surfacePill: 'rgba(255, 255, 255, 0.08)',
        border: 'rgba(255, 255, 255, 0.14)',
        borderAlt: 'rgba(255, 255, 255, 0.08)',
        text: '#ffffff',
        textSecondary: '#a1a1aa',
        textMuted: '#71717a',
      },
    },
  },

  // 5. Ultra High-Contrast Sunlight Day
  'high-contrast-day': {
    id: 'high-contrast-day',
    name: 'روز با وضوح فوق‌العاده (نور شدید)',
    englishName: 'Ultra High-Contrast Sunlight Day',
    description: 'کنتراست حداکثری، متن‌های کاملاً مشکی، خطوط ضخیم و رنگ‌های پررنگ جهت خوانایی کامل در محیط‌های پرنور اداری',
    category: 'light',
    isDark: false,
    badge: 'نور شدید آفتاب ☀️',
    previewColor: '#ffffff',
    cardPreviewColor: '#f1f5f9',
    accentColor: '#0284c7',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#0284c7',
        primaryHover: '#0369a1',
        accent: '#0284c7',
        accentGlow: 'rgba(2, 132, 199, 0.35)',
        background: '#ffffff',
        backgroundHeader: 'rgba(255, 255, 255, 0.99)',
        surface: '#f8fafc',
        surfaceHover: '#e2e8f0',
        surfaceAlt: '#ffffff',
        surfacePill: '#e2e8f0',
        border: '#334155',
        borderAlt: '#64748b',
        text: '#000000',
        textSecondary: '#0f172a',
        textMuted: '#1e293b',
      },
    },
  },

  // 6. Executive Emerald Light
  'solar-light': {
    id: 'solar-light',
    name: 'روشن اداری زمردی',
    englishName: 'Executive Emerald Light',
    description: 'کنتراست بالا و وضوح فوق‌العاده با پس‌زمینه سفید خالص و رنگ تاکیدی زمردی برای فضاهای پرنور اداری',
    category: 'light',
    isDark: false,
    badge: 'روشن زمردی 🍃',
    previewColor: '#f2f7f5',
    cardPreviewColor: '#ffffff',
    accentColor: '#047857',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#047857',
        primaryHover: '#065f46',
        accent: '#047857',
        accentGlow: 'rgba(4, 120, 87, 0.25)',
        background: '#f2f7f5',
        backgroundHeader: 'rgba(255, 255, 255, 0.98)',
        surface: '#ffffff',
        surfaceHover: '#eaf6f0',
        surfaceAlt: '#f0fdf4',
        surfacePill: '#e2e8f0',
        border: '#cbd5e1',
        borderAlt: '#99f6e4',
        text: '#022c22',
        textSecondary: '#0f172a',
        textMuted: '#334155',
      },
    },
  },

  // 7. Shiraz Spring Daylight
  'shiraz-daylight': {
    id: 'shiraz-daylight',
    name: 'روشن بهار شیراز',
    englishName: 'Shiraz Spring Daylight',
    description: 'تم دلنشین روز با الهام از آسمان بهاری و ترنج شیراز، فیروزه‌ای آسمانی و نارنجی',
    category: 'light',
    isDark: false,
    badge: 'بهار شیراز 🌸',
    previewColor: '#f8fafc',
    cardPreviewColor: '#ffffff',
    accentColor: '#0284c7',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#0284c7',
        primaryHover: '#0369a1',
        accent: '#0284c7',
        accentGlow: 'rgba(2, 132, 199, 0.22)',
        background: '#f8fafc',
        backgroundHeader: 'rgba(255, 255, 255, 0.98)',
        surface: '#ffffff',
        surfaceHover: '#f0f9ff',
        surfaceAlt: '#f8fafc',
        surfacePill: '#e0f2fe',
        border: '#bae6fd',
        borderAlt: '#e0f2fe',
        text: '#082f49',
        textSecondary: '#0c4a6e',
        textMuted: '#334155',
      },
    },
  },

  // 8. White-Label Metro Corporate (Tehran / Corporate)
  'metro-corporate': {
    id: 'metro-corporate',
    name: 'سازمانی مترو پایتخت (آبی سورمه‌ای)',
    englishName: 'Corporate Capital Metro',
    description: 'تم مدرن و ساختاریافته سازمانی با پالت سورمه‌ای عمیق، لاجوردی و کنتراست شکیل برای مانیتورهای عریض',
    category: 'dark',
    isDark: true,
    badge: 'سازمانی رسمی 🏢',
    previewColor: '#070d1e',
    cardPreviewColor: '#172554',
    accentColor: '#3b82f6',
    tokens: {
      ...DEFAULT_DESIGN_TOKENS,
      colors: {
        ...DEFAULT_DESIGN_TOKENS.colors,
        primary: '#3b82f6',
        primaryHover: '#2563eb',
        accent: '#3b82f6',
        accentGlow: 'rgba(59, 130, 246, 0.35)',
        background: '#070d1e',
        backgroundHeader: 'rgba(7, 13, 30, 0.94)',
        surface: 'rgba(30, 58, 138, 0.14)',
        surfaceHover: 'rgba(30, 58, 138, 0.22)',
        surfaceAlt: 'rgba(30, 58, 138, 0.08)',
        surfacePill: 'rgba(59, 130, 246, 0.12)',
        border: 'rgba(96, 165, 250, 0.22)',
        borderAlt: 'rgba(96, 165, 250, 0.12)',
        text: '#f8fafc',
        textSecondary: '#cbd5e1',
        textMuted: '#94a3b8',
      },
    },
  },
};
