/**
 * Initial Production Module Catalog for Shiraz Metro OCC Design System
 * Extracted directly from existing operational and presentation UI components.
 * Pure presentation definitions referencing real underlying components without business logic entanglement.
 */

import { ModuleDefinition, ModuleCategory } from '../types/schema';

export const INITIAL_APPLICATION_MODULES: Record<string, ModuleDefinition> = {
  // ==========================================
  // 1. GLOBAL MODULES
  // ==========================================
  'global.header': {
    id: 'global.header',
    name: 'سربرگ یکپارچه سراسری (Global Application Header)',
    englishName: 'Global Application Header',
    category: 'global',
    sourceComponentId: 'global.header',
    version: '2.2.0',
    description: 'سربرگ جامع عملیاتی شامل برندینگ مترو شیراز، ساعت LED رسمی ایران، کنترل‌های شبیه‌سازی، هشدار تعویض نوبت، دید در شب OCC، تغییر تم و ناوبری تب‌ها',
    icon: 'Globe',
    tags: ['سراسری', 'هدر', 'برندینگ', 'ساعت LED', 'شبیه‌سازی', 'اعلان شیفت', 'دید در شب', 'ناوبری'],
    capabilities: {
      draggable: false,
      resizable: false,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: false,
      removable: false,
      responsive: true,
    },
    props: {
      title: 'سامانه ی جامع سیر و حرکت',
      subtitle: 'سازمان حمل و نقل ریلی شیراز',
      lineTitle: 'خط ۱',
      lineRouteText: 'احسان ⇄ دستغیب (۲۰ ایستگاه)',
      showLogo: true,
      showLiveClock: true,
      showSimControls: true,
      showFloatingClockToggle: true,
      showShiftAlerts: true,
      showNightVisionToggle: true,
      showThemeToggle: true,
      showThemeModalButton: true,
      showArchitectureButton: true,
      showFullscreenToggle: true,
      showNavTabs: true,
      showTelemetryPills: true,
      sticky: true,
      variant: 'glass',
      compact: false,
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'مرکز فرمان OCC',
      isGlobal: true,
      isCustom: false,
      businessPattern: 'Master Application Shell Header & Operational Bar',
    },
  },

  'global.status_bar': {
    id: 'global.status_bar',
    name: 'نوار وضعیت عملیاتی بلادرنگ (Global Operational Status Bar)',
    englishName: 'Global Operational Status Bar',
    category: 'global',
    sourceComponentId: 'global.status_bar',
    version: '2.1.0',
    description: 'نوار وضعیت بالای صفحه شامل تیکر وضعیت خط ۱، تعداد قطارهای فعال، سرفاصله زمانی و تاخیر شبکه',
    icon: 'Activity',
    tags: ['سراسری', 'وضعیت', 'سرفاصله', 'ناوگان', 'شبکه'],
    capabilities: {
      draggable: false,
      resizable: false,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: false,
      removable: false,
      responsive: true,
    },
    props: {
      showOccStatus: true,
      showActiveTrainsCount: true,
      showHeadwayTimer: true,
      showNetworkLatency: true,
      showEmergencyTicker: true,
      tickerText: 'احسان ⇄ دستغیب: کلیه اعزام‌ها با سرفاصله ۱۵ دقیقه طبق گراف مصوب در جریان است.',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'مرکز فرمان OCC',
      isGlobal: true,
      isCustom: false,
      businessPattern: 'OCC Real-time Operational Telemetry Bar',
    },
  },

  'global.footer': {
    id: 'global.footer',
    name: 'پاورقی و اطلاعات سامانه (Global System Footer)',
    englishName: 'Global System Footer',
    category: 'global',
    sourceComponentId: 'global.footer',
    version: '2.1.0',
    description: 'پاورقی رسمی با متون حق نشر، نگارش سامانه، نشان محیط و میانبرهای عملیاتی',
    icon: 'Shield',
    tags: ['سراسری', 'فوتر', 'نسخه', 'امنیت'],
    capabilities: {
      draggable: false,
      resizable: false,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: false,
      removable: false,
      responsive: true,
    },
    props: {
      copyrightText: 'تمامی حقوق متعلق به سازمان حمل و نقل ریلی شهرداری شیراز است.',
      systemVersionText: 'نسخه ۲.۱.۰ (OCC Master Suite)',
      showEnvironmentBadge: true,
      showShortcutsHint: true,
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'مرکز فرمان OCC',
      isGlobal: true,
      isCustom: false,
      businessPattern: 'Application Shell Footer',
    },
  },

  // ==========================================
  // 2. OCC MODULES
  // ==========================================
  'occ.synoptic_canvas': {
    id: 'occ.synoptic_canvas',
    name: 'نقشه سیناپتیک زنده خط ۱ (Live Synoptic Track Map)',
    englishName: 'Live Synoptic Track Map',
    category: 'occ',
    sourceComponentId: 'app.live_occ',
    version: '2.1.0',
    description: 'نمایش سیناپتیک تعاملی ۲۰ ایستگاه خط ۱ (احسان تا دستغیب)، موقعیت زنده قطارها و اشغال بلاک‌های ترانزیت',
    icon: 'Train',
    tags: ['OCC', 'ایستگاه‌ها', 'بلاک', 'سیناپتیک', 'نقشه'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'نقشه سیناپتیک و سیر زنده قطارهای خط ۱',
      showStationsList: true,
      showTrainPositions: true,
      autoRefreshIntervalSeconds: 3,
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'مرکز کنترل OCC',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Synoptic Track Presentation Layer',
    },
  },

  'occ.terminal_dispatch': {
    id: 'occ.terminal_dispatch',
    name: 'مانیتور دیسپچینگ پایانه‌های احسان و دستغیب (Terminal Dispatch Monitor)',
    englishName: 'Terminal Dispatch Monitor',
    category: 'occ',
    sourceComponentId: 'app.dispatch_board',
    version: '2.1.0',
    description: 'تابلوی پایش اعزام و پذیرش همزمان پایانه‌های سرخط، زمان ورود/خروج و وضعیت راهبران',
    icon: 'Table',
    tags: ['OCC', 'پایانه', 'احسان', 'دستغیب', 'اعزام'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'پایش اعزام و پذیرش پایانه‌های احسان و دستغیب',
      filterTerminal: 'all',
      showDelaysOnly: false,
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'دیسپچینگ خط ۱',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Terminal Dispatch Table Presentation',
    },
  },

  'occ.scada_telemetry': {
    id: 'occ.scada_telemetry',
    name: 'سیستم تله‌متری و توان الکتریکی SCADA (SCADA Electrical Telemetry)',
    englishName: 'SCADA Electrical Telemetry',
    category: 'occ',
    sourceComponentId: 'widgets.metric_strip',
    version: '2.1.0',
    description: 'پایش ولتاژ ریل سوم (750V DC)، پست‌های کشش الکتریکی (TSS) و وضعیت سیستم تهویه تونل',
    icon: 'Gauge',
    tags: ['OCC', 'SCADA', 'برق', 'تله‌متری', 'پست کشش'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      voltageDC: 750,
      activeSubstations: 12,
      powerStatus: 'نرمال',
      ventilationActive: true,
    },
    defaultLayout: { colSpan: 6 },
    metadata: {
      author: 'مهندسی تاسیسات و توان OCC',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'SCADA Telemetry Widget',
    },
  },

  'occ.radio_comms': {
    id: 'occ.radio_comms',
    name: 'مرکز ارتباطات بی‌سیم و رادیویی OCC (Radio Comms Hub)',
    englishName: 'Radio Comms Hub',
    category: 'occ',
    sourceComponentId: 'feedback.alert_banner',
    version: '2.1.0',
    description: 'پنل صوتی و رادیویی دیسپچر با کانال‌های اختصاصی قطارها، پایانه احسان، دستغیب و تیم امداد',
    icon: 'Radio',
    tags: ['OCC', 'رادیو', 'بی‌سیم', 'کانال', 'صوت'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'کانال ارتباطی رادیویی دیسپچینگ (CH-01 Master)',
      activeChannel: 'CH-01 (Dispatching)',
      driverCountOnChannel: 14,
    },
    defaultLayout: { colSpan: 6 },
    metadata: {
      author: 'مخابرات و رادیو OCC',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Radio Channel Presentation',
    },
  },

  // ==========================================
  // 3. START SHIFT MODULES
  // ==========================================
  'start_shift.roster_card': {
    id: 'start_shift.roster_card',
    name: 'کارت نوبت‌کاری و ثبت حضور راهبر (Start Shift Roster Card)',
    englishName: 'Start Shift Roster Card',
    category: 'start_shift',
    sourceComponentId: 'content.stat_card',
    version: '2.1.0',
    description: 'کارت وضعیت ورود راهبر، تایید سلامت هوشیاری، تخصیص لوحه و فعال‌سازی شیفت عملیاتی',
    icon: 'Users',
    tags: ['شیفت', 'راهبر', 'حضور', 'نوبت‌کاری'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'وضعیت آماده‌باش شیفت جاری',
      value: '۳۶ راهبر حاضر',
      subtitle: '۱۰۰٪ انطباق با جدول شیفت صبح و عصر',
      badge: 'تکمیل',
      badgeType: 'positive',
    },
    defaultLayout: { colSpan: 4 },
    metadata: {
      author: 'امور راهبران مترو',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Driver Shift Attendance Presentation',
    },
  },

  'start_shift.driver_assignment': {
    id: 'start_shift.driver_assignment',
    name: 'کارت تخصیص راهبر به رام قطار (Driver Assignment Card)',
    englishName: 'Driver Assignment Card',
    category: 'start_shift',
    sourceComponentId: 'app.driver_management',
    version: '2.1.0',
    description: 'نمای بصری جفت‌سازی راهبر با شماره قطار، سرفاصله اعزام، پایانه مبدا و راهبر رزرو',
    icon: 'Users',
    tags: ['راهبر', 'قطار', 'تخصیص', 'لوحه'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'تخصیص راهبران به رام‌های قطار خط ۱',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'امور راهبران',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Driver Assignment Presentation Card',
    },
  },

  'start_shift.queue_roster': {
    id: 'start_shift.queue_roster',
    name: 'صف راهبران آماده و رزرو پایانه (Shift Standby Queue)',
    englishName: 'Shift Standby Queue',
    category: 'start_shift',
    sourceComponentId: 'layout.card',
    version: '2.1.0',
    description: 'لیست اولویت‌بندی شده راهبران آماده اعزام، راهبران استراحت فعال و نیروهای رزرو اضطراری',
    icon: 'Users',
    tags: ['صف', 'رزرو', 'استراحت', 'پایانه'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: true,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'صف راهبران آماده و رزرو پایانه احسان',
      subtitle: 'ترتیب اعزام و زمان انتظار شیفت',
      badge: '۸ راهبر آماده',
      variant: 'glass',
    },
    defaultLayout: { colSpan: 6 },
    metadata: {
      author: 'امور راهبران',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Driver Standby Queue Presentation',
    },
  },

  'start_shift.mobile_dashboard': {
    id: 'start_shift.mobile_dashboard',
    name: 'داشبورد همراه شروع شیفت راهبر (Mobile Shift Dashboard)',
    englishName: 'Mobile Shift Dashboard',
    category: 'start_shift',
    sourceComponentId: 'app.driver_management',
    version: '2.1.0',
    description: 'نمای بهینه‌سازی شده موبایل جهت مشاهده برنامه شخصی، تایید شیفت و اعلام حضور راهبر در پایانه',
    icon: 'Smartphone',
    tags: ['موبایل', 'شیفت', 'راهبر', 'شخصی'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'داشبورد همراه راهبران خط ۱',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'امور راهبران',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Mobile Driver Shift Dashboard Presentation',
    },
  },

  // ==========================================
  // 4. DISPATCH MODULES
  // ==========================================
  'dispatch.board_view': {
    id: 'dispatch.board_view',
    name: 'لوحه رسمی اعزام و پذیرش (Dispatch Board View)',
    englishName: 'Dispatch Board View',
    category: 'dispatch',
    sourceComponentId: 'app.dispatch_board',
    version: '2.1.0',
    description: 'جدول کامل اعزام روزانه پایانه‌های احسان و دستغیب همراه با وضعیت راهبران، جانشین رزرو و استانداردهای چاپی',
    icon: 'Table',
    tags: ['دیسپچینگ', 'لوحه', 'سیر', 'اعزام', 'پایانه'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'لوحه رسمی اعزام و پذیرش قطارهای خط ۱',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'مرکز دیسپچینگ',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Official Dispatch Timetable Presentation',
    },
  },

  'dispatch.delay_tracker': {
    id: 'dispatch.delay_tracker',
    name: 'پایشگر تاخیرات ساعتی اعزام (Hourly Dispatch Delay Tracker)',
    englishName: 'Hourly Dispatch Delay Tracker',
    category: 'dispatch',
    sourceComponentId: 'app.oee_analytics',
    version: '2.1.0',
    description: 'نمودار ستونی پایش تاخیرات در ساعات اوج و غیراوج صبح و عصر بر حسب دقیقه و علت ریشه‌ای',
    icon: 'BarChart3',
    tags: ['تاخیر', 'پایش', 'ساعت اوج', 'گراف'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'تحلیل تاخیرات ساعتی اعزام از پایانه‌ها',
    },
    defaultLayout: { colSpan: 6 },
    metadata: {
      author: 'مهندسی سیر و حرکت',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Delay Analytics Presentation',
    },
  },

  // ==========================================
  // 5. DASHBOARD & CARDS MODULES
  // ==========================================
  'dashboard.operational_summary': {
    id: 'dashboard.operational_summary',
    name: 'نوار سریع آمار سیر (Metro Metric Strip)',
    englishName: 'Metro Metric Strip',
    category: 'dashboard',
    sourceComponentId: 'widgets.metric_strip',
    version: '2.1.0',
    description: 'نوار ۴ تایی خلاصه وضعیت قطارهای در سیر، راهبران، سرفاصله و درصد انطباق با گراف',
    icon: 'Activity',
    tags: ['داشبورد', 'آمار', 'سیر', 'سرفاصله'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      activeTrains: 14,
      totalDrivers: 36,
      headwayMinutes: 15,
      complianceRate: '۹۹.۲٪',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'OCC Master',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Operational Summary Metric Strip',
    },
  },

  'dashboard.alert_notice': {
    id: 'dashboard.alert_notice',
    name: 'بنر پیام و هشدار فوری (Alert Banner)',
    englishName: 'Alert Banner',
    category: 'dashboard',
    sourceComponentId: 'feedback.alert_banner',
    version: '2.1.0',
    description: 'نمایش پیام‌های فوری، هشدارها و اطلاعیه‌های مهم دیسپچینگ به کاربران',
    icon: 'AlertTriangle',
    tags: ['پیام', 'هشدار', 'دیسپچینگ', 'اطلاعیه'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      severity: 'info',
      title: 'وضعیت نرمال خط ۱',
      message: 'کلیه اعزام‌ها از پایانه‌های احسان و دستغیب مطابق گراف سیر در حال اجرا می‌باشد.',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'OCC Master',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Alert Banner Presentation',
    },
  },

  'cards.kpi_stat': {
    id: 'cards.kpi_stat',
    name: 'کارت شاخص و متریک (KPI Stat Card)',
    englishName: 'KPI Stat Card',
    category: 'cards',
    sourceComponentId: 'content.stat_card',
    version: '2.1.0',
    description: 'نمایش عددی شاخص‌های کلیدی، درصد پیشرفت، برچسب روند و انیمیشن نورانی',
    icon: 'BarChart3',
    tags: ['شاخص', 'کارت', 'متریک', 'درصد'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'شاخص آمادگی ناوگان',
      value: '۹۴.۲٪',
      subtitle: '۲۰ رام از ۲۲ رام آماده سیر',
      badge: '+۱.۸٪',
      badgeType: 'positive',
    },
    defaultLayout: { colSpan: 4 },
    metadata: {
      author: 'OCC Master',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'KPI Presentation Card',
    },
  },

  'cards.glass_container': {
    id: 'cards.glass_container',
    name: 'پنل شیشه‌ای دیزاین (Glass Card Container)',
    englishName: 'Glass Card Container',
    category: 'cards',
    sourceComponentId: 'layout.card',
    version: '2.1.0',
    description: 'کانتینر چندمنظوره با افکت شیشه‌ای، بردر گرادینت و قابلیت پذیرش المان‌های فرزند',
    icon: 'Square',
    tags: ['کانتینر', 'شیشه‌ای', 'پنل', 'کارت'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: true,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'پنل اطلاعات عملیاتی',
      subtitle: 'توضیحات و گزارش اختصاصی',
      badge: 'فعال',
      variant: 'glass',
    },
    defaultLayout: { colSpan: 6 },
    metadata: {
      author: 'Design System Team',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Glass Container Primitive',
    },
  },

  // ==========================================
  // 6. CHARTS & ANALYTICS MODULES
  // ==========================================
  'charts.oee_productivity': {
    id: 'charts.oee_productivity',
    name: 'داشبورد بهره‌وری OEE (OEE Analytics)',
    englishName: 'OEE Analytics',
    category: 'charts',
    sourceComponentId: 'app.oee_analytics',
    version: '2.1.0',
    description: 'تحلیل عمیق بهره‌وری ناوگان، زمان سیر بازرگانی، توقفات فنی و نمودار ماری خط ۱',
    icon: 'Gauge',
    tags: ['OEE', 'بهره‌وری', 'تحلیل', 'نمودار'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'داشبورد جامع بهره‌وری OEE خط ۱',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'مهندسی بهره‌وری',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'OEE Analytics Dashboard Presentation',
    },
  },

  // ==========================================
  // 7. STATUS & TIME MODULES
  // ==========================================
  'status.occ_master_clock': {
    id: 'status.occ_master_clock',
    name: 'ساعت زنده مرکز فرمان (OCC Clock)',
    englishName: 'OCC Clock',
    category: 'status',
    sourceComponentId: 'widgets.clock',
    version: '2.1.0',
    description: 'نمایش زنده زمان استاندارد با ارقام خوانای فارسی و هماهنگی دقیق با سرور دیسپچینگ',
    icon: 'Clock',
    tags: ['ساعت', 'زمان', 'OCC', 'بلادرنگ'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      showSeconds: true,
    },
    defaultLayout: { colSpan: 4 },
    metadata: {
      author: 'OCC Master',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Master Clock Presentation',
    },
  },

  // ==========================================
  // 8. OPERATIONS & FLEET MODULES
  // ==========================================
  'operations.fleet_management': {
    id: 'operations.fleet_management',
    name: 'مدیریت ناوگان و دپو (Fleet Management)',
    englishName: 'Fleet Management',
    category: 'operations',
    sourceComponentId: 'app.fleet_management',
    version: '2.1.0',
    description: 'پنل مدیریت ۲۲ رام قطار شامل امتیاز سلامت، کارت سرویس دوره‌ای و گزارش دپوی احسان و دستغیب',
    icon: 'Train',
    tags: ['ناوگان', 'قطار', 'دپو', 'تعمیرات'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'مدیریت ناوگان و وضعیت ۲۲ رام قطار خط ۱',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'امور ناوگان و دپو',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Fleet & Depot Management Presentation',
    },
  },

  'operations.schedule_generator': {
    id: 'operations.schedule_generator',
    name: 'ژنراتور زمان‌بندی (Schedule Generator)',
    englishName: 'Schedule Generator',
    category: 'operations',
    sourceComponentId: 'app.schedule_generator',
    version: '2.1.0',
    description: 'ابزار طراحی و تولید ماتریس زمان‌بندی اعزام، تغییر سرفاصله و تخصیص قطارها و راهبران',
    icon: 'Calendar',
    tags: ['زمان‌بندی', 'گراف', 'سرفاصله', 'برنامه‌ریزی'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'ژنراتور هوشمند زمان‌بندی و گراف سیر',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'مهندسی سیر و حرکت',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Schedule Planning Presentation',
    },
  },

  // ==========================================
  // 9. LAYOUT PRIMITIVES MODULES
  // ==========================================
  'layout.section_header': {
    id: 'layout.section_header',
    name: 'سربرگ بخش (Section Header)',
    englishName: 'Section Header',
    category: 'layout',
    sourceComponentId: 'layout.section_header',
    version: '2.1.0',
    description: 'سربرگ تفکیک‌کننده برای داشبوردها و بخش‌های مختلف صفحه با بج و توضیحات',
    icon: 'Heading',
    tags: ['چیدمان', 'سربرگ', 'عنوان'],
    capabilities: {
      draggable: true,
      resizable: true,
      editable: true,
      styleable: true,
      nestable: false,
      duplicatable: true,
      removable: true,
      responsive: true,
    },
    props: {
      title: 'پایش ناوگان و سلامت فنی قطارهای خط ۱',
      subtitle: 'مانیتورینگ ۲۲ رام قطار و کارت‌های تعمیرات دوره‌ای',
      badge: 'دپوی احسان و دستغیب',
    },
    defaultLayout: { colSpan: 12 },
    metadata: {
      author: 'Design System Team',
      isGlobal: false,
      isCustom: false,
      businessPattern: 'Section Header Primitive',
    },
  },
};
