/**
 * Default Navigation Configuration
 * Configuration-driven navigation for Shiraz Metro and configurable white-label installations.
 */

import { NavigationConfig } from '../types/schema';

export const DEFAULT_NAVIGATION_CONFIG: NavigationConfig = {
  position: 'top',
  collapsible: true,
  showBadges: true,
  showIcons: true,
  items: [
    {
      id: 'live',
      label: 'سیر زنده و مرکز پایش',
      englishLabel: 'Live OCC Dashboard',
      icon: 'Activity',
      route: '/live',
      visible: true,
      order: 1,
      badge: 'زنده',
      badgeColor: 'bg-emerald-500/20 text-emerald-300 border border-emerald-400/30',
      description: 'نقشه ۲۰ ایستگاه، موقعیت قطارها و لاگ‌های دیسپچری',
      permission: 'occ.view',
    },
    {
      id: 'board',
      label: 'لوحه اعزام و پذیرش',
      englishLabel: 'Daily Dispatch Board',
      icon: 'Table',
      route: '/board',
      visible: true,
      order: 2,
      badge: 'لوحه روز',
      badgeColor: 'bg-sky-500/20 text-sky-300 border border-sky-400/30',
      description: 'لوحه رسمی روزانه پایانه‌های احسان و دستغیب و خروجی چاپی A3',
      permission: 'dispatch.manage',
    },
    {
      id: 'scheduler',
      label: 'زمان‌بندی و گراف سیر',
      englishLabel: 'Schedule & Timetable',
      icon: 'Calendar',
      route: '/scheduler',
      visible: true,
      order: 3,
      badge: 'هوشمند',
      badgeColor: 'bg-purple-500/20 text-purple-300 border border-purple-400/30',
      description: 'تولید و بهینه‌سازی گراف حرکت و زمان‌بندی قطارها',
      permission: 'schedule.edit',
    },
    {
      id: 'fleet',
      label: 'مدیریت ناوگان و دپو',
      englishLabel: 'Rolling Stock Fleet',
      icon: 'Train',
      route: '/fleet',
      visible: true,
      order: 4,
      badge: '۲۲ رام',
      badgeColor: 'bg-indigo-500/20 text-indigo-300 border border-indigo-400/30',
      description: 'وضعیت سلامت فنی، کارت سرویس و تعمیرات قطارها',
      permission: 'fleet.view',
    },
    {
      id: 'drivers',
      label: 'راهبران و شیفت‌ها',
      englishLabel: 'Driver Dossiers & Shift Roster',
      icon: 'Users',
      route: '/drivers',
      visible: true,
      order: 5,
      badge: 'مناقصه',
      badgeColor: 'bg-amber-400/20 text-amber-300 border border-amber-400/40',
      description: 'پرونده راهبران، مناقصه شیفت، گراف تبادل و نوبت‌کاری',
      permission: 'personnel.manage',
    },
    {
      id: 'oee',
      label: 'داشبورد بهره‌وری OEE',
      englishLabel: 'OEE Analytics & KPIs',
      icon: 'Gauge',
      route: '/oee',
      visible: true,
      order: 6,
      badge: '۸۸.۴٪',
      badgeColor: 'bg-emerald-500/20 text-emerald-300 border border-emerald-400/40',
      description: 'شاخص‌های کلیدی بهره‌وری عملیاتی ناوگان و راهبران با Recharts',
      permission: 'analytics.view',
    },
    {
      id: 'logs',
      label: 'دفتر وقایع و بی‌سیم OCC',
      englishLabel: 'Incident Logs & Radio Feed',
      icon: 'BookOpen',
      route: '/logs',
      visible: true,
      order: 7,
      badgeColor: 'bg-rose-500 text-white font-black animate-pulse shadow-sm',
      description: 'ثبت حوادث، هشدارهای ایمنی و پیام‌های دیسپچری',
      permission: 'logs.view',
    },
    {
      id: 'sandbox',
      label: 'توسعه و شبیه‌ساز',
      englishLabel: 'Developer Sandbox',
      icon: 'Cpu',
      route: '/sandbox',
      visible: true,
      order: 8,
      badge: 'DevTools',
      badgeColor: 'bg-indigo-500/20 text-indigo-300 border border-indigo-400/40',
      description: 'تولید راهبران مجازی با نام ایرانی، تست استرس و پاکسازی',
      permission: 'dev.sandbox',
    },
    {
      id: 'design_system',
      label: 'سیستم دیزاین و سازنده UI',
      englishLabel: 'Visual Design Builder',
      icon: 'Sparkles',
      route: '/design-system',
      visible: true,
      order: 9,
      badge: 'Visual Builder',
      badgeColor: 'bg-gradient-to-r from-emerald-400 to-sky-400 text-slate-950 font-black shadow-md animate-pulse',
      description: 'سازنده بصری چیدمان، ویرایشگر تم و توکن‌ها، ناوبری و خروجی JSON نسخه دار',
      permission: 'design.builder',
    },
  ],
};
