/**
 * Operational Template Catalog
 * Ready-to-deploy page and layout presets for Shiraz Metro OCC command and monitoring.
 */

import { TemplateDefinition } from '../types/schema';

export const OPERATIONAL_TEMPLATES: Record<string, TemplateDefinition> = {
  occ_master: {
    id: 'occ_master',
    name: 'مرکز فرمان و کنترل ترافیک خط ۱ (OCC Master)',
    englishName: 'OCC Line 1 Master Command',
    description: 'چیدمان کامل مرکز کنترل شامل پایش زنده سیر، نوار شاخص‌های لحظه‌ای، گراف اعزام قطارها و هشدارهای رخداد',
    category: 'occ',
    previewColor: '#0a0f1d',
    recommendedThemeId: 'occ-dark',
    columns: 12,
    gap: 'md',
    tags: ['OCC', 'پایش زنده', 'ترافیک', 'اصلی'],
    nodes: [
      {
        id: 'tpl_node_metrics',
        componentId: 'analytics.metric_strip',
        title: 'شاخص‌های کلیدی سیر لحظه‌ای',
        props: {
          activeTrains: 14,
          totalDrivers: 36,
          headwayMinutes: 15,
          complianceRate: '۹۹.۴٪',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_alert',
        componentId: 'feedback.alert_banner',
        title: 'پیام عملیاتی سامانه',
        props: {
          severity: 'info',
          title: 'وضعیت نرمال خط ۱',
          message: 'سیر قطارها در بلاک‌های ۲۰گانه طبق برنامه زمانی در جریان است.',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_kpi1',
        componentId: 'content.stat_card',
        title: 'شاخص آمادگی ناوگان',
        props: {
          title: 'شاخص آمادگی ناوگان',
          value: '۹۴.۲٪',
          subtitle: '۲۰ رام قطار فعال و آماده اعزام',
          badge: 'پایدار',
          badgeType: 'positive',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_kpi2',
        componentId: 'content.stat_card',
        title: 'سرفاصله زمانی میانگین',
        props: {
          title: 'سرفاصله زمانی میانگین',
          value: '۱۵ دقیقه',
          subtitle: 'سرعت بازرگانی ۳۲ کیلومتر بر ساعت',
          badge: 'مصوب',
          badgeType: 'neutral',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_kpi3',
        componentId: 'content.stat_card',
        title: 'انطباق شیفت راهبران',
        props: {
          title: 'انطباق شیفت راهبران',
          value: '۱۰۰٪',
          subtitle: 'راهبران و رزروها در پایانه احسان و دستغیب',
          badge: 'کامل',
          badgeType: 'positive',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_live_occ',
        componentId: 'app.live_occ',
        title: 'پایش و کنترل لحظه‌ای خط ۱ (OCC)',
        props: {
          title: 'پایش و کنترل لحظه‌ای خط ۱ (OCC)',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  fleet_depot: {
    id: 'fleet_depot',
    name: 'مدیریت ناوگان و تعمیرات دپو (Fleet & Depot)',
    englishName: 'Fleet & Depot Maintenance',
    description: 'چیدمان تخصصی پایش ۲۲ رام قطار خط ۱، وضعیت تعمیرات دوره‌ای، کیلومتراژ و بازرسی فنی',
    category: 'fleet',
    previewColor: '#07161b',
    recommendedThemeId: 'cyber-navy',
    columns: 12,
    gap: 'md',
    tags: ['ناوگان', 'دپو', 'تعمیرات', 'قطارها'],
    nodes: [
      {
        id: 'tpl_node_fleet_header',
        componentId: 'layout.section_header',
        title: 'سربرگ پایش ناوگان و دپو',
        props: {
          title: 'پایش ناوگان و سلامت فنی قطارهای خط ۱',
          subtitle: 'مانیتورینگ ۲۲ رام قطار و کارت‌های تعمیرات دوره‌ای دپوی احسان و دستغیب',
          badge: 'دپوی احسان و دستغیب',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_fleet_kpi1',
        componentId: 'content.stat_card',
        title: 'قطارهای در سیر فعال',
        props: {
          title: 'قطارهای در سیر فعال',
          value: '۱۴ رام',
          subtitle: 'از ایستگاه ۱ تا ۲۰',
          badge: 'سیر تجاری',
          badgeType: 'positive',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_fleet_kpi2',
        componentId: 'content.stat_card',
        title: 'آماده‌به‌کار در دپو',
        props: {
          title: 'آماده‌به‌کار در دپو',
          value: '۶ رام',
          subtitle: 'دپوی احسان (۳) / دپوی دستغیب (۳)',
          badge: 'آماده باش',
          badgeType: 'neutral',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_fleet_kpi3',
        componentId: 'content.stat_card',
        title: 'تحت تعمیرات دوره‌ای',
        props: {
          title: 'تحت تعمیرات دوره‌ای',
          value: '۲ رام',
          subtitle: 'سرویس سطح ۳ و تعویض کفشک',
          badge: 'کارگاه دپو',
          badgeType: 'warning',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_fleet_app',
        componentId: 'app.fleet_management',
        title: 'مدیریت ناوگان و دپو',
        props: {
          title: 'مدیریت ناوگان و دپو',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  dispatch_roster: {
    id: 'dispatch_roster',
    name: 'مدیریت شیفت و دیسپچینگ راهبران (Driver Dispatch)',
    englishName: 'Driver Scheduling & Dispatch',
    description: 'پنل تخصصی چینش و واگذاری شیفت‌های راهبران، کشیک‌ها، احراز صلاحیت و وضعیت حضور در پایانه‌ها',
    category: 'dispatch',
    previewColor: '#0b1320',
    recommendedThemeId: 'occ-dark',
    columns: 12,
    gap: 'md',
    tags: ['راهبران', 'شیفت', 'دیسپچینگ', 'برنامه‌ریزی'],
    nodes: [
      {
        id: 'tpl_node_disp_header',
        componentId: 'layout.section_header',
        title: 'سربرگ مدیریت راهبران',
        props: {
          title: 'برنامه‌ریزی و اعزام شیفت راهبران قطار شهری شیراز',
          subtitle: 'تخصیص راهبران به رام‌های قطار و ثبت تحویل و تحول کابین',
          badge: 'شیفت صبح و عصر',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_disp_app',
        componentId: 'app.driver_management',
        title: 'مدیریت و برنامه‌ریزی راهبران',
        props: {
          title: 'مدیریت و برنامه‌ریزی راهبران',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  incident_emergency: {
    id: 'incident_emergency',
    name: 'مرکز فرماندهی حوادث و شرایط اضطراری (Incident Command)',
    englishName: 'Incident & Emergency Command',
    description: 'پیکربندی با اولویت ایمنی و تفکیک سریع آلارم‌ها، هشدارهای آتش‌نشانی، تهویه و دستورالعمل‌های بحران',
    category: 'incident',
    previewColor: '#1a0d0d',
    recommendedThemeId: 'high-contrast',
    columns: 12,
    gap: 'md',
    tags: ['بحران', 'حوادث', 'اضطراری', 'ایمنی'],
    nodes: [
      {
        id: 'tpl_node_inc_banner',
        componentId: 'feedback.alert_banner',
        title: 'آماده‌باش ستاد بحران',
        props: {
          severity: 'warning',
          title: 'پایش پروتکل‌های ایمنی خط ۱',
          message: 'کلیه پایانه‌ها و پست‌های کشش الکتریکی در وضعیت نظارت ویژه قرار دارند.',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_inc_kpi1',
        componentId: 'content.stat_card',
        title: 'وضعیت سیگنالینگ ATP',
        props: {
          title: 'وضعیت سیگنالینگ ATP',
          value: 'عادی و پایدار',
          subtitle: 'پوشش کامل رادیویی تترا',
          badge: 'پایدار',
          badgeType: 'positive',
        },
        layout: { colSpan: 6 },
        visible: true,
      },
      {
        id: 'tpl_node_inc_kpi2',
        componentId: 'content.stat_card',
        title: 'پست‌های رکتیفایر و برق بالاسری',
        props: {
          title: 'پست‌های رکتیفایر و برق بالاسری',
          value: '۱۵۰۰ ولت DC',
          subtitle: '۷ پست فوق توزیع برق‌دار',
          badge: 'نرمال',
          badgeType: 'positive',
        },
        layout: { colSpan: 6 },
        visible: true,
      },
      {
        id: 'tpl_node_inc_occ',
        componentId: 'app.live_occ',
        title: 'مرکز پایش و کنترل لحظه‌ای خط ۱ (OCC)',
        props: {
          title: 'مرکز پایش و کنترل لحظه‌ای خط ۱ (OCC)',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  analytics_kpi: {
    id: 'analytics_kpi',
    name: 'داشبورد جامع آمار و شاخص‌های سیر (Analytics & KPIs)',
    englishName: 'Operations Analytics & Reports',
    description: 'تمرکز بر مقایسه سرفاصله، سرعت تجاری، توزیع مسافری و گزارش‌های گراف سیر روزانه',
    category: 'analytics',
    previewColor: '#0a141c',
    recommendedThemeId: 'metro-amber',
    columns: 12,
    gap: 'lg',
    tags: ['تحلیل', 'KPI', 'گزارش', 'آمار'],
    nodes: [
      {
        id: 'tpl_node_an_strip',
        componentId: 'analytics.metric_strip',
        title: 'نوار سریع آمار سیر',
        props: {
          activeTrains: 14,
          totalDrivers: 36,
          headwayMinutes: 15,
          complianceRate: '۹۹.۲٪',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_an_kpi1',
        componentId: 'content.stat_card',
        title: 'مسافران جابجا شده امروز',
        props: {
          title: 'مسافران جابجا شده امروز',
          value: '۱۴۲,۵۰۰ سفر',
          subtitle: '+۴.۲٪ نسبت به روز قبل',
          badge: 'رشد مسافری',
          badgeType: 'positive',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_an_kpi2',
        componentId: 'content.stat_card',
        title: 'دقت اعزام به موقع (On-Time)',
        props: {
          title: 'دقت اعزام به موقع (On-Time)',
          value: '۹۸.۸٪',
          subtitle: 'کمتر از ۶۰ ثانیه انحراف',
          badge: 'عالی',
          badgeType: 'positive',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_an_kpi3',
        componentId: 'content.stat_card',
        title: 'میانگین سرعت سیر',
        props: {
          title: 'میانگین سرعت سیر',
          value: '۳۴.۵ km/h',
          subtitle: 'سرعت حداکثر ۷۰ km/h',
          badge: 'استاندارد',
          badgeType: 'neutral',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_an_app',
        componentId: 'app.schedule_graph',
        title: 'گراف زمانی-مکانی حرکت قطارها',
        props: {
          title: 'گراف زمانی-مکانی حرکت قطارها',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },
};
