/**
 * Operational Template Catalog
 * Composed directly from the Shiraz Metro OCC Module Library.
 * Ready-to-deploy page presets representing core railway command workflows.
 */

import { TemplateDefinition } from '../types/schema';

export const OPERATIONAL_TEMPLATES: Record<string, TemplateDefinition> = {
  occ_dashboard_template: {
    id: 'occ_dashboard_template',
    name: 'قالب داشبورد مرکز فرمان (OCC Dashboard Template)',
    englishName: 'OCC Dashboard Template',
    description: 'چیدمان اصلی پایش بلادرنگ مرکز فرمان شامل نوار آمار لحظه‌ای سیر، بنر هشدارهای دیسپچینگ، نقشه سیناپتیک ۲۰ ایستگاه و متریک‌های کلیدی',
    category: 'occ',
    previewColor: '#0a0f1d',
    recommendedThemeId: 'occ-dark',
    columns: 12,
    gap: 'md',
    tags: ['OCC', 'داشبورد', 'پایش زنده', 'سیناپتیک', 'ماژولار'],
    nodes: [
      {
        id: 'tpl_node_metrics',
        componentId: 'widgets.metric_strip',
        moduleId: 'dashboard.operational_summary',
        title: 'نوار سریع آمار سیر خط ۱',
        props: {
          activeTrains: 14,
          totalDrivers: 36,
          headwayMinutes: 15,
          complianceRate: '۹۹.۴٪',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_alert',
        componentId: 'feedback.alert_banner',
        moduleId: 'dashboard.alert_notice',
        title: 'پیام دیسپچینگ مرکزی',
        props: {
          severity: 'info',
          title: 'وضعیت خط ۱: پایدار و نرمال',
          message: 'سیر قطارها در بلاک‌های ۲۰گانه طبق برنامه زمانی با سرفاصله ۱۵ دقیقه در جریان است.',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_node_kpi1',
        componentId: 'content.stat_card',
        moduleId: 'cards.kpi_stat',
        title: 'شاخص آمادگی ناوگان',
        props: {
          title: 'شاخص آمادگی ناوگان',
          value: '۹۴.۲٪',
          subtitle: '۲۰ رام قطار فعال و آماده اعزام',
          badge: 'پایدار',
          badgeType: 'positive',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_kpi2',
        componentId: 'content.stat_card',
        moduleId: 'cards.kpi_stat',
        title: 'سرفاصله زمانی میانگین',
        props: {
          title: 'سرفاصله زمانی میانگین',
          value: '۱۵ دقیقه',
          subtitle: 'سرعت بازرگانی ۳۲ کیلومتر بر ساعت',
          badge: 'مصوب',
          badgeType: 'neutral',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_kpi3',
        componentId: 'content.stat_card',
        moduleId: 'cards.kpi_stat',
        title: 'انطباق شیفت راهبران',
        props: {
          title: 'انطباق شیفت راهبران',
          value: '۱۰۰٪',
          subtitle: 'راهبران و رزروها در پایانه احسان و دستغیب',
          badge: 'کامل',
          badgeType: 'positive',
        },
        layout: { colSpan: 4 },
        visible: true,
      },
      {
        id: 'tpl_node_live_occ',
        componentId: 'app.live_occ',
        moduleId: 'occ.synoptic_canvas',
        title: 'پایش و کنترل لحظه‌ای خط ۱ (OCC)',
        props: {
          title: 'مرکز پایش و کنترل لحظه‌ای خط ۱ (OCC)',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  dispatch_template: {
    id: 'dispatch_template',
    name: 'قالب دیسپچینگ و اعزام قطارها (Dispatch Template)',
    englishName: 'Dispatch Template',
    description: 'ترکیب ماژول‌های لوحه رسمی روزانه پایانه‌های احسان و دستغیب، صف راهبران آماده و پایشگر تاخیرات ساعتی',
    category: 'dispatch',
    previewColor: '#0b1320',
    recommendedThemeId: 'occ-dark',
    columns: 12,
    gap: 'md',
    tags: ['دیسپچینگ', 'لوحه', 'سیر', 'اعزام', 'پایانه'],
    nodes: [
      {
        id: 'tpl_disp_header',
        componentId: 'layout.section_header',
        moduleId: 'layout.section_header',
        title: 'سربرگ لوحه رسمی اعزام',
        props: {
          title: 'لوحه رسمی اعزام و پذیرش قطارهای خط ۱',
          subtitle: 'سیر روزانه پایانه‌های احسان و دستغیب همراه با تاییدیه راهبر و جانشین رزرو',
          badge: 'لوحه فعال روز',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_disp_board',
        componentId: 'app.dispatch_board',
        moduleId: 'dispatch.board_view',
        title: 'لوحه اعزام و پذیرش قطارها',
        props: {
          title: 'لوحه رسمی اعزام و پذیرش قطارهای خط ۱',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_disp_delays',
        componentId: 'app.oee_analytics',
        moduleId: 'dispatch.delay_tracker',
        title: 'پایشگر تاخیرات اعزام',
        props: {
          title: 'تحلیل تاخیرات ساعتی اعزام از پایانه‌ها',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  operations_template: {
    id: 'operations_template',
    name: 'قالب جامع عملیات و ناوگان (Operations Template)',
    englishName: 'Operations Template',
    description: 'چیدمان یکپارچه مدیریت ناوگان و دپو، ژنراتور زمان‌بندی و پرونده نوبت‌کاری راهبران خط ۱',
    category: 'fleet',
    previewColor: '#07161b',
    recommendedThemeId: 'cyber-navy',
    columns: 12,
    gap: 'md',
    tags: ['عملیات', 'ناوگان', 'دپو', 'راهبران'],
    nodes: [
      {
        id: 'tpl_ops_header',
        componentId: 'layout.section_header',
        moduleId: 'layout.section_header',
        title: 'سربرگ مدیریت عملیات و ناوگان',
        props: {
          title: 'مرکز مدیریت عملیات، ناوگان و راهبران خط ۱',
          subtitle: 'پایش ۲۲ رام قطار، کارت‌های تعمیراتی و برنامه نوبت‌کاری پرسنل',
          badge: 'دپوی احسان و دستغیب',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_ops_fleet',
        componentId: 'app.fleet_management',
        moduleId: 'operations.fleet_management',
        title: 'مدیریت ناوگان و دپو',
        props: {
          title: 'مدیریت ناوگان و وضعیت ۲۲ رام قطار خط ۱',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_ops_drivers',
        componentId: 'app.driver_management',
        moduleId: 'start_shift.driver_assignment',
        title: 'مدیریت راهبران و شیفت‌ها',
        props: {
          title: 'مدیریت راهبران و تخصیص به قطارها',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  analytics_template: {
    id: 'analytics_template',
    name: 'قالب تحلیل و آمار عملکردی (Analytics Template)',
    englishName: 'Analytics Template',
    description: 'تحلیل پیشرفته شاخص‌های بهره‌وری OEE، گراف حرکت زمانی-مکانی ماری و توزیع تقاضای مسافری',
    category: 'analytics',
    previewColor: '#0a141c',
    recommendedThemeId: 'metro-amber',
    columns: 12,
    gap: 'lg',
    tags: ['تحلیل', 'OEE', 'ماری', 'آمار', 'سیر'],
    nodes: [
      {
        id: 'tpl_an_strip',
        componentId: 'widgets.metric_strip',
        moduleId: 'dashboard.operational_summary',
        title: 'نوار سریع آمار سیر',
        props: {
          activeTrains: 14,
          totalDrivers: 36,
          headwayMinutes: 15,
          complianceRate: '۹۹.۲٪',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
      {
        id: 'tpl_an_oee',
        componentId: 'app.oee_analytics',
        moduleId: 'charts.oee_productivity',
        title: 'داشبورد بهره‌وری جامع OEE',
        props: {
          title: 'داشبورد جامع بهره‌وری OEE خط ۱',
        },
        layout: { colSpan: 12 },
        visible: true,
      },
    ],
  },

  mobile_operations_template: {
    id: 'mobile_operations_template',
    name: 'قالب عملیات همراه راهبر (Mobile Operations Template)',
    englishName: 'Mobile Operations Template',
    description: 'طراحی ویژه موبایل و تبلت برای راهبران و پرسنل پایانه جهت ثبت شروع شیفت، مشاهده لوحه شخصی و اعلان‌های فوری',
    category: 'minimal',
    previewColor: '#0f172a',
    recommendedThemeId: 'occ-dark',
    columns: 1,
    gap: 'sm',
    tags: ['موبایل', 'همراه', 'راهبر', 'شیفت'],
    nodes: [
      {
        id: 'tpl_mob_alert',
        componentId: 'feedback.alert_banner',
        moduleId: 'dashboard.alert_notice',
        title: 'پیام شیفت',
        props: {
          severity: 'info',
          title: 'شیفت صبح خط ۱ فعال است',
          message: 'لطفاً پیش از سوار شدن، تاییدیه هوشیاری و چک‌لیست کابین را تکمیل نمایید.',
        },
        layout: { colSpan: 1 },
        visible: true,
      },
      {
        id: 'tpl_mob_kpi',
        componentId: 'content.stat_card',
        moduleId: 'start_shift.roster_card',
        title: 'وضعیت شیفت شما',
        props: {
          title: 'وضعیت آماده‌باش شیفت جاری',
          value: 'تخصیص یافته',
          subtitle: 'رام قطار ۰۴ - پایانه احسان',
          badge: 'شیفت صبح',
          badgeType: 'positive',
        },
        layout: { colSpan: 1 },
        visible: true,
      },
      {
        id: 'tpl_mob_dashboard',
        componentId: 'app.driver_management',
        moduleId: 'start_shift.mobile_dashboard',
        title: 'داشبورد همراه شروع شیفت',
        props: {
          title: 'داشبورد همراه راهبران خط ۱',
        },
        layout: { colSpan: 1 },
        visible: true,
      },
    ],
  },
};
